// Validation configuration - Add this file to .gitignore for privacy

export const INAPPROPRIATE_WORDS = [
  // Profanity & Slang
  "fuck",
  "shit",
  "damn",
  "bitch",
  "ass",
  "bastard",
  "dick",
  "cock",
  "pussy",
  "whore",
  "slut",
  "crap",
  "bloody",
  "bollocks",

  // Sexual content
  "sex",
  "porn",
  "nude",
  "naked",
  "xxx",
  "adult",
  "onlyfans",
  "stripper",
  "escort",

  // Violence & Death
  "kill",
  "murder",
  "death",
  "suicide",
  "abuse",
  "slaughter",
  "gun",
  "knife",
  "bomb",
  "explosion",

  // Drugs
  "drug",
  "cocaine",
  "marijuana",
  "weed",
  "heroin",
  "meth",
  "lsd",
  "ecstasy",

  // Hate speech & extremism
  "hate",
  "racist",
  "nazi",
  "terrorist",
  "isis",
  "klan",
  "hitler",

  // Fake or joke job titles
  "ninja",
  "rockstar",
  "guru",
  "wizard",
  "overlord",
  "badass",
  "hacker",
  "slayer",
  "warrior",
  "pirate",
  "god",
  "queen",
  "king",
  "lord",
  "master",
  "dictator",
  "champion",

  // Other inappropriate or joke words
  "boobs",
  "fart",
  "poop",
  "pee",
  "wtf",
  "omg",
  "hell",
  "satan",
  "devil",
  "evil",
];


export const JOB_KEYWORDS = [
  // Job Titles
  "engineer",
  "developer",
  "analyst",
  "manager",
  "director",
  "coordinator",
  "specialist",
  "consultant",
  "administrator",
  "assistant",
  "associate",
  "executive",
  "officer",
  "lead",
  "senior",
  "junior",
  "intern",
  "trainee",
  "designer",
  "architect",
  "scientist",
  "researcher",
  "technician",
  "representative",

  // Departments/Fields
  "sales",
  "marketing",
  "finance",
  "accounting",
  "human resources",
  "hr",
  "operations",
  "project",
  "product",
  "business",
  "data",
  "software",
  "web",
  "mobile",
  "frontend",
  "backend",
  "fullstack",
  "devops",
  "qa",
  "quality",
  "testing",
  "support",
  "customer",
  "service",
  "content",
  "social media",
  "digital",
  "graphic",
  "ui",
  "ux",

  // Professional Roles
  "nurse",
  "doctor",
  "teacher",
  "professor",
  "lawyer",
  "accountant",
  "chef",
  "mechanic",
  "electrician",
  "plumber",
  "carpenter",
  "pilot",
  "driver",

  // Technology Keywords
  "javascript",
  "python",
  "java",
  "react",
  "angular",
  "vue",
  "node",
  "php",
  "ruby",
  "golang",
  "rust",
  "swift",
  "kotlin",
  "typescript",
  "html",
  "css",
  "sql",
  "mongodb",
  "postgresql",
  "mysql",
  "redis",
  "docker",
  "kubernetes",
  "aws",
  "azure",
  "gcp",
  "cloud",
  "api",
  "rest",
  "graphql",
  "microservices",
  "machine learning",
  "artificial intelligence",
  "blockchain",
  "cybersecurity",
  "network",
  "database",
  "system",
  "infrastructure",

  // Add more keywords as needed
];

export const MEANINGLESS_PATTERNS = [
  /^[a-z]\1{2,}$/i, // Repeated characters like "aaa"
  /^[0-9]+$/, // Only numbers
  /^[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]+$/, // Only special characters
  /^(test|testing|abc|xyz|qwerty|asdf|zxcv|hello|hi|hey|yo)$/i, // Common test words
  /^(bla|blah|haha|lol|wtf|omg|idk|random|whatever)$/i, // Meaningless words
  /^(.)\1{4,}$/, // 5+ repeated characters
];

export const NAME_PATTERN = /^[A-Z][a-z]+ [A-Z][a-z]+$/; // Detects names like "John Smith"
